# ******************************************************************************
# File    : Makefile
# Date    : 2025-07-21 13:36 -0300
# GitHub  : https://github.com/computacaoraiz/CRpaic
# --------------------------------------------------
# This Makefile builds the CRpaic library, creating the static and dynamic
# library files to be incorporated into client programs. Currently, the only
# supported operating system is Linux.


# ******************************************************************************
# ** 1. Project and toolchain configuration                                   **
# ******************************************************************************

# Operational System in use (Linux is the only OS supported at moment):
OS := $(shell uname)
ifneq ($(OS), Linux)
    $(error CRpaic is supported only on Linux at the moment)
endif

# Version of CRpaic library:
VERSION       := $(shell awk '/STRING/ {gsub(/"/,"",$$3); print $$3}' \
                 include/CRpaic/CRpaic_version.h)
VERSION_MAJOR := $(word 1, $(subst ., , $(VERSION)))
VERSION_MINOR := $(word 2, $(subst ., , $(VERSION)))
VERSION_PATCH := $(word 3, $(subst ., , $(VERSION)))

# Just a check to verify if we are ready to build the correct version.
# This check will be removed in future version of this Makefile.
ifneq ($(VERSION), $(shell cat src/VERSION.TXT))
    $(error CRpaic_version.h VERSION ($(VERSION)) does not match with \
    src/VERSION.TXT ($(shell cat src/VERSION.TXT)))
endif

# C standard:
CSTD ?= gnu17

# Programs to use:
CC := gcc
AR := ar

# Directories for the build process:
SRCDIR   := src
INCDIR   := include
BUILDDIR := build
LIBDIR   := lib
DOCSDIR  := docs

# Compiler flags:
CFLAGS := -std=$(CSTD) -MMD -MP \
          -Wall -Wextra -Werror -Wconversion -Wunused-result

MODE ?= PRODUCTION
ifeq ($(MODE), DEBUG)
    CFLAGS += -ggdb -O0 -DDEBUG
else
    ifeq ($(MODE), PRODUCTION)
        CFLAGS += -O3
    else
        $(error Mode $(MODE) not recognized)
    endif
endif

# Compiler pre-processor flags:
CPPFLAGS := -I$(INCDIR)

# Linker flags:
LDFLAGS := 

# Libs flags;
LDLIBS := -lm -lX11 -lcrypt

# CRpaic lib name:
LIBNAME := CRpaic

# Directories for installation (/usr/local by default). DESTDIR is used
# by developer's and, normally, should be left empty.
PREFIX  ?= /usr/local
DESTDIR ?= 
MANDIR  ?= /share/man/man3

# ******************************************************************************
# ** 2. Source discovery and object mapping                                   **
# ******************************************************************************

# Recursive discovery off all source files:
SRCS := $(shell find $(SRCDIR) -name '*.c')

# Mapping of each source file to a specific matching object file:
OBJS := $(patsubst $(SRCDIR)/%.c, $(BUILDDIR)/%.o, $(SRCS))

# Mapping of each source file to a specific mathching PIC object file:
PICOBJS := $(patsubst $(SRCDIR)/%.c, $(BUILDDIR)/%.pic.o, $(SRCS))

# Dependencies list generated by the compiler (DO NOT use spaces):
DEPS := $(OBJS:.o=.d)

# Man pages files:
MANSSRC := $(wildcard $(DOCSDIR)/*.3)
MANS := $(wildcard $(DOCSDIR)/*.3.gz)
MANUAL := $(MANSSRC:.3=.3.gz)


# ******************************************************************************
# ** 3. Main targets and compilations rules                                   **
# ******************************************************************************

# Phony targets that are allways executed:
.PHONY: all static shared install uninstall mans clean version

# Default target: build static and shared libraries:
all: $(LIBDIR)/lib$(LIBNAME).a $(LIBDIR)/lib$(LIBNAME).so.$(VERSION) mans

# Target to build only the static library:
static: $(LIBDIR)/lib$(LIBNAME).a

# Target to build only the shared library:
shared: $(LIBDIR)/lib$(LIBNAME).so.$(VERSION)

# Target for the static library:
$(LIBDIR)/lib$(LIBNAME).a: $(OBJS)
	@printf "\n===> Processing %s <===\n" "$@"
	mkdir -p $(dir $@)
	@echo "AR $@"
	$(AR) rcs $@ $^

# Target for the shared library:
$(LIBDIR)/lib$(LIBNAME).so.$(VERSION): $(PICOBJS)
	@printf "\n===> Processing %s <===\n" "$@"
	mkdir -p $(dir $@)
	@echo "LD $@"
	$(CC) -shared -Wl,-soname,$(@F) -o $@ $^ $(LDFLAGS) $(LDLIBS)

# Target for objects compilation:
$(BUILDDIR)/%.o: $(SRCDIR)/%.c
	@printf "\n===> Processing %s <===\n" "$@"
	mkdir -p $(dir $@)
	@echo "CC $<"
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

# Target for PIC objects compilation:
$(BUILDDIR)/%.pic.o: $(SRCDIR)/%.c
	@printf "\n===> Processing %s <===\n" "$@"
	mkdir -p $(dir $@)
	@echo "CC (PIC) $<"
	$(CC) $(CPPFLAGS) $(CFLAGS) -fPIC -c -o $@ $<

# Targets for the man pages (more util to developers):
mans: $(MANUAL)

%.3.gz: %.3
	@gzip -ckf $< > $@

# Includes the dependencies files generated:
-include $(DEPS)


# ******************************************************************************
# ** 4. Installation                                                          **
# ******************************************************************************

# Installation
install: all
	@printf "\n===> Installing to %s <===\n" "$(PREFIX)"
	install -d $(DESTDIR)$(PREFIX)/lib
	install -d $(DESTDIR)$(PREFIX)/include/$(LIBNAME)
	install -m 644 \
	        $(LIBDIR)/lib$(LIBNAME).a $(DESTDIR)$(PREFIX)/lib
	install -m 755 \
	        $(LIBDIR)/lib$(LIBNAME).so.$(VERSION) $(DESTDIR)$(PREFIX)/lib
	ln -sf $(DESTDIR)$(PREFIX)/lib/lib$(LIBNAME).so.$(VERSION) \
	       $(DESTDIR)$(PREFIX)/lib/lib$(LIBNAME).so.$(VERSION_MAJOR)
	ln -sf $(DESTDIR)$(PREFIX)/lib/lib$(LIBNAME).so.$(VERSION_MAJOR) \
	       $(DESTDIR)$(PREFIX)/lib/lib$(LIBNAME).so
	find $(INCDIR) -type f -name "*.h" -exec sh -c '\
	     dest=$(DESTDIR)$(PREFIX)/include/$${1#$(INCDIR)/}; \
	     install -D -m 644 "$$1" "$$dest"' sh {} \;
	install -m 644 $(MANS) $(DESTDIR)$(PREFIX)$(MANDIR)
ifeq ($(OS), Linux)
	ldconfig $(DESTDIR)$(PREFIX)/lib
endif


# ******************************************************************************
# ** 5. Uninstallation                                                        **
# ******************************************************************************

# Uninstallation:
uninstall:
	@printf "\n===> Uninstalling from %s <===\n" "$(PREFIX)"
	rm -f $(DESTDIR)$(PREFIX)/lib/lib$(LIBNAME).*
	rm -f $(DESTDIR)$(PREFIX)/include/$(LIBNAME).h
	rm -fr $(DESTDIR)$(PREFIX)/include/$(LIBNAME)
	rm -f $(addprefix $(DESTDIR)$(PREFIX)$(MANDIR)/, $(notdir $(MANS)))
ifeq ($(OS), Linux)
	ldconfig $(DESTDIR)$(PREFIX)/lib
endif


# ******************************************************************************
# ** 6. Cleanup                                                               **
# ******************************************************************************

# Cleanup of files at the end of the build process (by default does not remove
# compressed man-pages from docs directory)
clean:
	find $(shell pwd) -type f -name "*~" -exec rm -fr {} \;
	rm -fr $(BUILDDIR)/CRpaic
	rm -f $(LIBDIR)/*.a
	rm -f $(LIBDIR)/*.so.$(VERSION)
	@#rm -f $(DOCSDIR)/*.3.gz


# ******************************************************************************
# ** 7. Version                                                               **
# ******************************************************************************

# Just check the VERSION used to build the library:
version:
	@echo $(VERSION)
