.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH CRPAIC_NEXT_PRIME 3 "2025-07-23" "CRpaic" "CRpaic User's Manual"
.SH NAME
crpaic_next_prime - returns the next prime number or 0
.SH SYNOPSIS
.nf
.B #include <CRpaic.h>
.PP
.BI "<TYPE> crpaic_next_prime (<TYPE> " n ");"
.PP
.BI "         char crpaic_next_prime_c (char " n ");"
.BI "unsigned char crpaic_next_prime_uc (unsigned char " n ");"
.PP
.BI "         short int crpaic_next_prime_si (short int " n ");"
.BI "unsigned short int crpaic_next_prime_usi (unsigned short int " n ");"
.PP
.BI "         int crpaic_next_prime_i (int " n ");"
.BI "unsigned int crpaic_next_prime_ui (unsigned int " n ");"
.PP
.BI "         long int crpaic_next_prime_li (long int " n ");"
.BI "unsigned long int crpaic_next_prime_uli (unsigned long int " n ");"
.PP
.BI "         long long int crpaic_next_prime_lli (long long int " n ");"
.BI "unsigned long long int crpaic_next_prime_ulli (unsigned long long int " n ");"
.fi
.SH DESCRIPTION
The
.BR crpaic_next_prime ()
function is a family of functions that takes as argument an integer number
.IR n
(of any integer data type) and return the next prime number greater than
.IR n
(returns the smallest prime greater than
.IR n ,
or the sentinel 0 if there is no such number in the type's range). The user can
pass the following types of integers:
.PP
    a) Signed or unsigned standard integers: char, short int, int, long int,
       and long long int;
.PP
    b) <stdint.h> integers: int8_t, uint8_t, int16_t, uint16_t, int32_t,
       uint32_t, int64_t, uint64_t.
.PP
The
.BR crpaic_next_prime ()
function is a _Generic macro that dispatches the argument
.IR n
to the correct specific function depending on the data type of
.IR n
(the argument). The client program can directly use one of the specific
functions to a given data type but, in general, it is recommended to use only
the generic
.BR crpaic_next_prime ()
macro in client programs.
.PP
Functions specific to a given data type are indicated by a standardized suffix,
for example,
.BR crpaic_next_prime_si ()
takes a short int as argument;
.BR crpaic_next_prime_uli ()
takes an unsigned long int as argument. OK, I know that embedding the
argument\(aqs data type in the function name (know as \(dqHungarian
Notation\(dq) is stupid. However, due to the purely academic nature of the
CRpaic library and to the use of the generic dispatch macro that works for any
numeric data type (integer and floating-point), I don\(aqt see any major
problems with this practice.
.SH RETURN VALUE
The
.BR crpaic_next_prime ()
return the next prime number greater than the argument
.IR n .
The TYPE of the return value will always be the same type as the argument, that
is, the type of the argument,
.IR n ,
determines the type of the returned value.
.PP
If, considering the limits of the integer data type used, there is no next prime
number, the function returns 0 (zero) as a sentinel value indicating that there
is no prime number greater than the argument
.IR n ,
in the numeric range of the data type used. See the following examples:
.PP
EXAMPLE 1: the variable \(dqresult1\(dq in the following expression will receive
the sentinel value 0 (zero), as there is no prime number greater than the
argument 253 in the numeric range of the uint8_t type (0 to 255) (please, note
that the types unsigned char and uint8_t are compatible):
.PP
.in +4n
.EX
unsigned char result1 = crpaic_next_prime((uint8_t) 253);
.EE
.in
.PP
EXAMPLE 2: the variable \(dqresult2\(dq in the following expression will receive
the value 257, as this is the next prime number greater than the argument 253 in
the numeric range of the short int type:
.PP
.in +4n
.EX
short int result2 = crpaic_next_prime((short int) 253);
.EE
.in
.PP
EXAMPLE 3: the variable \(dqresult3\(dq in the following expression will receive
the value 2, as this is the next prime number greater than the argument -1000 in
the numeric range of the int type:
.PP
.in +4n
.EX
int result3 = crpaic_next_prime(-1000);
.EE
.in
.SH ERRORS
On success,
.IR errno
is not modified. In case of failures,
.IR errno
is set to the following values:
.TP
.B ERANGE
Numerical result out of range. Indicates that there is no prime number greater
than the argument
.IR n
in the numeric range of the argument's data type; the function returns 0 (zero)
as a sentinel value.
.SH ATTRIBUTES
The
.BR crpaic_next_prime ()
is:
.TP
.BR Thread-Safe ?
Yes, this function is Multi Thread-Safe (MT-Safe).
.TP
.BR Reentrant ?
No, this function is not reentrant.
.PP
For more explanation about these concepts, see
.BR attributes (7).
.SH CONFORMING TO
Not applicable.
.SH EXAMPLE
.in +4n
.EX
#include <CRpaic.h>
#include <stdio.h>

int main (void)
{
    /* result1 gets 251 */
    uint8_t result1 = crpaic_next_prime((uint8_t) 250);
    if (!result1)
        printf(\(dqThere is no prime number greather than 250 in uint8_t.\\n\(dq);
    else
        printf(\(dqThe next prime number is %u.\\n\(dq, result1);

    /* result2 gets 0 (the sentinel value) */
    uint8_t result2 = crpaic_next_prime((uint8_t) 253);
    if (!result2)
        printf(\(dqThere is no prime number greather than 253 in uint8_t.\\n\(dq);
    else
        printf(\(dqThe next prime number is %u.\\n\(dq, result2);

    /* result3 gets 2 */
    long int result3 = crpaic_next_prime(-10000L);
    if (!result3)
        printf(\(dqThere is no prime number greather than -10000 in int.\\n\(dq);
    else
        printf(\(dqThe next prime number is %ld.\\n\(dq, result3);

    return 0;
}
.EE
.in
.SH APPLICATION USAGE
The argument
.IR n
can be of virtually any integer data type. It's best to use the generic dispatch
macro,
.BR crpaic_next_prime () ,
instead of using the specific functions.
.SH RATIONALE
Finding the next prime number greater than a given value is a necessary
operation in some situations in computing, for example, to determine the
appropriate number of buckets in a hash table, and therefore
.BR crpaic_next_prime ()
can be useful.
.SH BUGS
Please report bugs and other issues on
.URL "https://github.com/computacaoraiz/CRpaic/" "CRpaic's GitHub:"
.SH FUTURE DIRECTIONS
None.
.SH SEE ALSO
.BR crpaic_is_prime ()
.SH CHANGE HISTORY
First released in CRpaic version 2.0.0.
.SH COLOPHON
This page is part of CRpaic User\(aqs Manual
.IR man-pages .
A description of the project, information about reporting bugs, and the latest
version of this page, can be found at
.URL "https://github.com/computacaoraiz/CRpaic/" "CRpaic's GitHub".
