.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH GET_INT 3 "2024-11-23" "CRpaic" "CRpaic User's Manual"
.SH NAME
get_int \- prompts user for a line of text from stdin and returns the
equivalent int
.SH SYNOPSIS
.nf
.B #include <CRpaic.h>
.PP
.BI "int get_int (const char *" format ", ...);"
.fi
.SH DESCRIPTION
The
.BR get_int ()
function prompts user (with a message defined by
.IR format )
for a line of text from standard input and returns the equivalent int; if text
does not represent an int or would cause overflow, user is reprompted. If
line can\(aqt be read, return INT_MAX.
.PP
The prompt is formatted like
.BR printf (3).
.SH RETURN VALUE
The
.BR get_int ()
function return the int equivalent to the line read from stdin in
[INT_MIN, INT_MAX), on success, or INT_MAX on failure.
.SH BUGS
Please report bugs and other issues on
.URL "https://github.com/computacaoraiz/CRpaic/" "CRpaic's GitHub:"
.SH EXAMPLE
.in +4n
.EX
#include <CRpaic.h>
#include <stdio.h>

int main (void)
{
    /* Get an int from user */
    int i = get_int("Enter an int: ");

    /* Check if we get a valid int */
    if (i == INT_MAX)
    {
        fprintf(stderr, "Could not get an int.\\n");
        return 1;
    }

    printf("int: %d\\n", i);

    return 0;
}
.EE
.in
.SH SEE ALSO
.BR get_char (3),
.BR get_double (3),
.BR get_float (3),
.BR get_long (3),
.BR get_long_double (3),
.BR get_long_long (3),
.BR get_string (3),
.BR printf (3)
.SH COLOPHON
This page is part of CRpaic User\(aqs Manual
.IR man-pages .
A description of the project, information about reporting bugs, and the latest
version of this page, can be found at
.URL "https://github.com/computacaoraiz/CRpaic/" "CRpaic's GitHub".
